### ISSUE TITLE
Bad Profile error on iOS 14.6

### ISSUE THREAD

**Issue by euroboy** [WangGuibin/WebClipChangeAppLogo#1]
When trying to download the configuration file an error pops-up: "Bad Profile - This profile is corrupted and cannot be read". Any ideas why this happens?

**Comment by WangGuibin** [comment]
@euroboy hi,boy, Because I write this toy when the mobile phone system is iOS 14.3, can not guarantee that there will be other problems later, as far as I guess may be missing the necessary fields to configure, you can try the online tool I wrote, find the problem timely feedback, thank you

**Comment by euroboy** [comment]
Sorry, my bad. This happened because I was not adding an URL.
