### ISSUE TITLE
您好,看了您的文章,麻烦请教个问题

### ISSUE THREAD

**Issue by superPinannan** [WangGuibin/WebClipChangeAppLogo#2]
您好,我现在遇到了个问题,在14.6系统的手机上,有的手机会出现二次跳转的情况(点击图标先是白屏再跳转),看了您的demo,在14.6系统的手机上也存在这个问题,麻烦问一下关于14.0之后应用会二次跳转的问题,您有什么好的解决思路没

**Comment by WangGuibin** [comment]
@superPinannan 你好，iOS14.6可能需要多添加一个参数，URLScheme或者是universal link，你可以尝试一下

**Comment by WangGuibin** [comment]
参考 https://iconthemer.app/
