### ISSUE TITLE
iOS15二次跳转

### ISSUE THREAD

**Issue by wwangning** [WangGuibin/WebClipChangeAppLogo#3]
大神 用了你的demo  在iOS14系统上 用webclip打开app是正常的 但是在iOS15上打开app的时候 会先跳转到一个白色的空白页 然后才能打开app 请问这个要怎么解决哇

**Comment by WangGuibin** [comment]
貌似没啥办法 系统如此
> It does NOT work on iOS 14.5 and above, including iOS 15.
参考 https://iconthemer.app/
