### ISSUE TITLE
Mobileconfig signing

### ISSUE THREAD

**Issue by VladLikov** [WangGuibin/WebClipChangeAppLogo#5]
Hello, 

How to sign mobileconfig file? 

Thank you

**Comment by WangGuibin** [comment]
`Apple Configurator 2`  sign with `Apple Developer Certificate` , That's it

**Comment by VladLikov** [comment]
Is it possible to sign Mobileconfig inside the iOS App?

**Comment by WangGuibin** [comment]
This touches my knowledge blind spot. If you find a similar method, please let me know.
