### ISSUE TITLE
Safari浏览器打不开该网页，因为找不到服务器

### ISSUE THREAD

**Issue by Qu000** [WangGuibin/WebClipChangeAppLogo#6]
不填写URL，在下载的时候会报文件损坏，
随意填写URL会在打开的时候报错“Safari浏览器打不开该网页，因为找不到服务器”，
只能给URL赋值APP的scheme了，用scheme中转一次跳转......这会有一个停顿，而且不再是同一个后台应用

有什么方法解决吗

**Comment by WangGuibin** [comment]
如果你的系统不是介于iOS 14～14.5之间，这是没有办法的，系统如此。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: iOS_July ***@***.***&gt;
发送时间: 2022年3月1日 14:22
收件人: WangGuibin/WebClipChangeAppLogo ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [WangGuibin/WebClipChangeAppLogo] Safari浏览器打不开该网页，因为找不到服务器 (Issue #6)

**Comment by Qu000** [comment]
@WangGuibin 👌，明白了，谢谢
